name: Build image and push to Artifact Registry using Cloud Build

on:
  push:
    branches:
    - main

# TODO Convert some (all?) variables to secrets so they do not show up in logs?
env:
  PROJECT_ID: my-cloud-workstations-417118
  REGION: europe-west9
  IMAGE_NAME: code-oss-for-rust
  WORKLOAD_IDENTITY_PROVIDER: projects/249106907360/locations/global/workloadIdentityPools/github/providers/my-repo
  SERVICE_ACCOUNT_NAME: cloud-builder # with roles `Cloud Build Service Account` and `Viewer`

jobs:
  cloud-build:
    name: Setup, Build, and Push with Cloud Build
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write

    steps:
    # Checkout MUST come before auth.
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    # Configure Workload Identity Federation and generate an access token.
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
    
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Build image, tag and push to Artifact Registry
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "${REGION}-docker.pkg.dev/${PROJECT_ID}/docker/${IMAGE_NAME}:${GITHUB_SHA}" \
          --tag "${REGION}-docker.pkg.dev/${PROJECT_ID}/docker/${IMAGE_NAME}:latest"
